### ISSUE TITLE
/schedule page text wrapping

### ISSUE THREAD

**Issue by ghost** [code4lib/2018.code4lib.org#192]
Text blurbs in the boxes on the /schedule page are wrapping on character boundaries rather than word boundaries.

**Comment by phette23** [comment]
This seems to be the offending style (in main.scss):

```css
.sched-well p {
    line-height: 1.7em;
    font-size: .9em;
    word-break: break-all;
}
```

Removing that "break-all" fixes it. Any idea why we might need that? Looking at the 2017 site this line was set to `break-word` so we must have deliberately changed it.
