### ISSUE TITLE
Speaker institution overlap on speakers page

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2018.code4lib.org#266]
When clicking on the speakers, if the title breaks onto a third line then the institution text becomes overlapped. See attached screenshot. Tested in Chrome and Firefox.

![screen shot 2018-02-06 at 3 16 34 pm](https://user-images.githubusercontent.com/6903515/35882074-efc9edfe-0b50-11e8-92aa-a34ac16a127a.png)

**Comment by phette23** [comment]
Hmm seems like the opacity of the down arrow is overlapping and obscuring the institution text. Adding

```css
p.speaker-inst {
  position: relative;
  z-index: 100;
}
```

seems to fix it
